---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: chaosiq-agent
  namespace: chaosiq-agent
spec:
  privileged: false
  allowPrivilegeEscalation: false
  defaultAllowPrivilegeEscalation: false
  hostNetwork: false
  hostIPC: false
  hostPID: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAsNonRoot
  fsGroup:
    rule: RunAsAny
  volumes:
  - configMap
  - secret
  - downwardAPI
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chaosiq-agent-psp
  namespace: chaosiq-agent
rules:
- apiGroups:
  - policy
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - chaosiq-agent
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaosiq-agent-psp
  namespace: chaosiq-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chaosiq-agent-psp
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:authenticated
  namespace: chaosiq-agent
- kind: ServiceAccount
  name: chaosiq-agent
  namespace: chaosiq-agent
