---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chaosiq-agent-run
  namespace: chaostoolkit-run
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chaosiq-agent-crd
  namespace: chaostoolkit-crd
rules:
- apiGroups:
  - chaostoolkit.org
  resources:
  - chaosexperiments
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaosiq-agent-run
  namespace: chaostoolkit-run
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chaosiq-agent-run
subjects:
- kind: ServiceAccount
  name: chaosiq-agent
  namespace: chaosiq-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaosiq-agent-crd
  namespace: chaostoolkit-crd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chaosiq-agent-crd
subjects:
- kind: ServiceAccount
  name: chaosiq-agent
  namespace: chaosiq-agent