auths:
  {console_hostname}:
    type: bearer
    value: {token}
controls:
  chaosiq-cloud:
    features:
      publish: 'on'
      safeguards: 'on'
      workspace: 'on'
    provider:
      arguments:
        organizations:
        - default: true
          id: {org_id}
          name:
          teams:
          - default: true
            id: {team_id}
            name:
        url: {console_url}
        verify_tls: {verify_tls}
      module: chaoscloud.controls
      type: python
